#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

// Implemented by autogenerated benchmarking code.
pub trait WeightInfo {
	fn set_config_with_u32() -> Weight;
	fn set_config_with_weight() -> Weight;
	fn service_deferred() -> Weight;
	fn discard_deferred() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: XcmpQueue QueueConfig (r:1 w:1)
	// Proof Skipped: XcmpQueue QueueConfig (max_values: Some(1), max_size: None, mode: Measured)
	fn set_config_with_u32() -> Weight {
		// Minimum execution time: 4_088 nanoseconds.
		Weight::from_ref_time(4_368_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: XcmpQueue QueueConfig (r:1 w:1)
	// Proof Skipped: XcmpQueue QueueConfig (max_values: Some(1), max_size: None, mode: Measured)
	fn set_config_with_weight() -> Weight {
		// Minimum execution time: 4_111 nanoseconds.
		Weight::from_ref_time(4_326_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: XcmpQueue QueueConfig (r:1 w:0)
	// Proof Skipped: XcmpQueue QueueConfig (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: XcmpQueue DeferredXcmMessages (r:1 w:1)
	// Proof Skipped: XcmpQueue DeferredXcmMessages (max_values: None, max_size: None, mode: Measured)
	// Storage: XcmpQueue CounterForOverweight (r:1 w:1)
	// Proof: XcmpQueue CounterForOverweight (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	// Storage: XcmpQueue OverweightCount (r:1 w:1)
	// Proof Skipped: XcmpQueue OverweightCount (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: XcmpQueue Overweight (r:100 w:100)
	// Proof Skipped: XcmpQueue Overweight (max_values: None, max_size: None, mode: Measured)
	fn service_deferred() -> Weight {
		// Minimum execution time: 90_934_683 nanoseconds.
		Weight::from_ref_time(91_491_151_000 as u64)
			.saturating_add(T::DbWeight::get().reads(104 as u64))
			.saturating_add(T::DbWeight::get().writes(103 as u64))
	}
	// Storage: XcmpQueue DeferredXcmMessages (r:1 w:1)
	// Proof Skipped: XcmpQueue DeferredXcmMessages (max_values: None, max_size: None, mode: Measured)
	fn discard_deferred() -> Weight {
		// Minimum execution time: 62_131_073 nanoseconds.
		Weight::from_ref_time(63_092_826_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
}

impl WeightInfo for () {
	// Storage: XcmpQueue QueueConfig (r:1 w:1)
	// Proof Skipped: XcmpQueue QueueConfig (max_values: Some(1), max_size: None, mode: Measured)
	fn set_config_with_u32() -> Weight {
		// Minimum execution time: 4_088 nanoseconds.
		Weight::from_ref_time(4_368_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(1 as u64))
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
	// Storage: XcmpQueue QueueConfig (r:1 w:1)
	// Proof Skipped: XcmpQueue QueueConfig (max_values: Some(1), max_size: None, mode: Measured)
	fn set_config_with_weight() -> Weight {
		// Minimum execution time: 4_111 nanoseconds.
		Weight::from_ref_time(4_326_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(1 as u64))
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
	// Storage: XcmpQueue QueueConfig (r:1 w:0)
	// Proof Skipped: XcmpQueue QueueConfig (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: XcmpQueue DeferredXcmMessages (r:1 w:1)
	// Proof Skipped: XcmpQueue DeferredXcmMessages (max_values: None, max_size: None, mode: Measured)
	// Storage: XcmpQueue CounterForOverweight (r:1 w:1)
	// Proof: XcmpQueue CounterForOverweight (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	// Storage: XcmpQueue OverweightCount (r:1 w:1)
	// Proof Skipped: XcmpQueue OverweightCount (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: XcmpQueue Overweight (r:100 w:100)
	// Proof Skipped: XcmpQueue Overweight (max_values: None, max_size: None, mode: Measured)
	fn service_deferred() -> Weight {
		// Minimum execution time: 90_934_683 nanoseconds.
		Weight::from_ref_time(91_491_151_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(104 as u64))
			.saturating_add(RocksDbWeight::get().writes(103 as u64))
	}
	// Storage: XcmpQueue DeferredXcmMessages (r:1 w:1)
	// Proof Skipped: XcmpQueue DeferredXcmMessages (max_values: None, max_size: None, mode: Measured)
	fn discard_deferred() -> Weight {
		// Minimum execution time: 62_131_073 nanoseconds.
		Weight::from_ref_time(63_092_826_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(1 as u64))
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
}
